/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AgentToolSourceMcp {
    'kind': AgentToolSourceMcpKindEnum;
    /**
     * MCP server name that provided the tool.
     */
    'server_name': string;
    /**
     * Tool name before MCP qualification.
     */
    'original_name': string;
}

export const AgentToolSourceMcpKindEnum = {
    MCP: 'mcp'
} as const;

export type AgentToolSourceMcpKindEnum = typeof AgentToolSourceMcpKindEnum[keyof typeof AgentToolSourceMcpKindEnum];
