/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentToolCategory } from './agent-tool-category';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentToolSource } from './agent-tool-source';

/**
 * Summary of one effective model-callable tool exposed to an agent stage.
 */
export interface AgentToolSummary {
    /**
     * Exposed model-facing tool name, for example `apply_patch` or `mcp__filesystem__read_file`.
     */
    'name': string;
    /**
     * Model-facing tool description.
     */
    'description': string;
    'source': AgentToolSource;
    'category': AgentToolCategory;
    /**
     * True once this tool has been invoked during the stage.
     */
    'invoked': boolean;
}
