/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AgentToolSourceNative {
    'kind': AgentToolSourceNativeKindEnum;
}

export const AgentToolSourceNativeKindEnum = {
    NATIVE: 'native'
} as const;

export type AgentToolSourceNativeKindEnum = typeof AgentToolSourceNativeKindEnum[keyof typeof AgentToolSourceNativeKindEnum];
