/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingSpeed } from './billing-speed';
// May contain unused imports in some cases
// @ts-ignore
import type { ReasoningEffort } from './reasoning-effort';

/**
 * Provider, model, and request-control metadata recorded for a stage attempt.
 */
export interface StageModelUsage {
    'mode': string;
    'provider'?: string | null;
    'model'?: string | null;
    'reasoning_effort'?: ReasoningEffort | null;
    'speed'?: BillingSpeed | null;
}
