/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Scope for disk resource metrics.
 */

export const SystemDiskResourceScope = {
    STORAGE_FILESYSTEM: 'storage_filesystem'
} as const;

export type SystemDiskResourceScope = typeof SystemDiskResourceScope[keyof typeof SystemDiskResourceScope];
